name: Trigger auto deployment for hr-portal-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/hr-portal-backend-AutoDeployTrigger-2d94dd87-b89b-48e4-b28e-873149222884.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.HRPORTALBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HRPORTALBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HRPORTALBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: sphrportalacr.azurecr.io
          registryUsername: ${{ secrets.HRPORTALBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HRPORTALBACKEND_REGISTRY_PASSWORD }}
          containerAppName: hr-portal-backend
          resourceGroup: hr-portal
          imageToBuild: sphrportalacr.azurecr.io/hr-portal-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


